# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d620b03f1ed784e2cfd72a30c983b1c77485616d1db3422c55354e930a69a5bdda997a44a1f829bd59cf8a3e2356287be166ff1456c9cb62ebae257f524ecc5

test:
  secret_key_base: 38c556961de5c7bb672753bf4409061402920fafaedc9aaacb8b002025a98ef5a17f0d1bbf82a12d855e66fb6884e39ae3dcd7220cb64a857914cb980dce3467

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
